### ISSUE TITLE
Weather -page is showing forecast for only 3 days

### ISSUE THREAD

**Issue by AnttiRumpunen** [smartmet-jm/weather-app#15]
On friday (12.5.) I can see only fri-sun weather forecast. 

At first I can see all 5 days, but then after some sort of update I can see only 3 days. Happens on both Android and IOS.

**Comment by evnurm-cgi** [comment]
I tested the application with a few different forecast time period lengths and found the following:
- when requesting **3** days, the server returns **3** days
- when requesting **4** days, the server returns **4** days
- when requesting **5** days, the server returns **5** days
- when requesting **6** days, the server returns **5** days
- when requesting **10** days, the server returns **5** days

Not sure if it matters but this test was performed on a Monday (May 15) and the last day returned was Friday (May 19). This should be tested on other days of the week as well. However, this suggests that the problem is caused by the data/server instead of the mobile application itself.

**Comment by AnttiRumpunen** [comment]
Most likely issue in data, not in app.
